name: WatchUrStep2
version: @version@
main: xyz.acxd.watchurstep2.Main
api-version: 1.16
authors: [ Scaffolding ]
description: Watch Ur Step 2, now with configurable options
website: https://acxd.xyz
